### ISSUE TITLE
[tracker] Improvement of `ModuleAnalyzer`

### ISSUE THREAD

**Issue by picnixz** [sphinx-doc/sphinx#11688]
This issue is kind of an "internal" issue because the `ModuleAnalyzer` is probably one of the most obscure and complex component of autodoc. Its purpose is to extract lines where methods, properties etc are defined and keep them so that autodoc and viewcode extensions can use them. In addition, I would like to keep this issue opened in order to track the tasks to do for the `ModuleAnalyzer`.

From what I see and know, here are the improvements that should (and sometimes must) be made:

* [ ] Address properties and class attributes detection: https://github.com/sphinx-doc/sphinx/issues/11279
* [ ] Support parsing `if TYPE_CHECKING` guarded blocks in order to track imported types (see https://github.com/sphinx-doc/sphinx/issues/11652#issuecomment-1707736322). This is also an alternative to https://github.com/sphinx-doc/sphinx/issues/11687, or can be used in conjunction if the static analysis fails. 
* [ ] Support subclassing of `ModuleAnalyzer` so that extensions can use it. Currently, it's very hard to actually subclass existing implementations of Sphinx components such as autodoc documenters because the implementation is not modular enough. While it could be a design choice for some cases (e.g., the couple writer-builder), it is very frustrating that "standalone" classes cannot be easily extendable. In particular, I would suggest a public API allowing the user to specify the module analyzer class to use.
