### ISSUE TITLE
[tracker] [tests] Python test suite reliability: striving for non-flaky, parallelizable, random-orderable tests.

### ISSUE THREAD

**Issue by jayaddison** [sphinx-doc/sphinx#12191]
This is an umbrella issue to track progress making the Sphinx test suite reliable.  That means:

  * No flaky tests.
  * Tests can run in parallel.
  * Tests are independent of each other.

Regarding the last item: test independence is important to ensure that each test is checking the behaviours it claims to, and does not inadvertently rely on the side-effects of some other test.  Similarly, a test must not begin failing if any other test is run before it -- if it does, that could mean (but does not definitely mean) that the application's behaviour itself may vary based on the order in which code is evaluated.

It might seem like there are a large number of items here!  However, please bear in mind that we have a total of more than 2000 individual `pytest` test cases that run.

# Test flakiness

- [x] [`test_build_linkcheck.test_connect_to_selfsigned_fails`](https://github.com/sphinx-doc/sphinx/issues/12038) (pr: #12166)
- [x] [`test_build_linkcheck.test_defaults`](https://github.com/sphinx-doc/sphinx/issues/12159) (pr: #12166)
- [x] [`test_build_linkcheck.test_linkcheck_exclude_documents`](https://github.com/sphinx-doc/sphinx/issues/12188) (pr: #12189)
- [ ] [`test_numfig_disabled_warn`](https://github.com/sphinx-doc/sphinx/issues/14104) (pr: #14107)
- [x] [`test_n_slowest_value`](https://github.com/sphinx-doc/sphinx/issues/14109) (pr: #14110)
- [ ] ... report another? 

# Test parallelization

- [x] [`tests.test_builders.test_build_linkcheck`](https://github.com/sphinx-doc/sphinx/issues/12122) (pr: #12126)
- [ ] ... report another?

# Test independence

- [x] [`tests.test_builders.test_build_text.py`](https://github.com/sphinx-doc/sphinx/issues/12120) (pr: #12868)
- [ ] [`tests.test_domains.test_domain_cpp`](https://github.com/sphinx-doc/sphinx/issues/12121) (pr: #12187)
- [ ] [`tests.test_builders.test_build_html`](https://github.com/sphinx-doc/sphinx/pull/12118) (pr: #12118)
- [x] [`tests.test_builders.test_build_html_download`](https://github.com/sphinx-doc/sphinx/pull/12119) (pr: #12119)
- [ ] ... report another?

**Comment by AA-Turner** [comment]
We should aim to make the test roots source directories read-only. This would help reliability as we can assert that state does not change. It also would speed up the tests as we can avoid copying every test root tree.

A patch to track tests that add new files to source directories (~15 currently)

```patch
Subject: [PATCH] Track new files in test srcdirs
---
Index: sphinx/testing/fixtures.py
<+>UTF-8
===================================================================
diff --git a/sphinx/testing/fixtures.py b/sphinx/testing/fixtures.py
--- a/sphinx/testing/fixtures.py	(revision c0681ed22dd28c4009a352aaa453c204cdadfbbd)
+++ b/sphinx/testing/fixtures.py	(revision 6a733c958d017877a86b7619559a38e5d13cd19d)
@@ -153,8 +153,20 @@
     """
     args, kwargs = app_params
     app_ = make_app(*args, **kwargs)
+    old = frozenset(app_.srcdir.rglob('*'))
+
     yield app_
 
+    new = old - set(app_.srcdir.rglob('*'))
+    new = new - frozenset(app_.srcdir.joinpath('_build').rglob('*'))
+    new = frozenset(p for p in new if p.is_file() and p.parent.name != '__pycache__')
+    if new:
+        from pathlib import Path
+        path_san = app_.srcdir.as_posix().replace('/', '~').replace(':', '')
+        filename = f'added~{path_san}~{hash(new)}.txt'
+        Path(filename).write_text('\n'.join(sorted(map(str, new))), encoding='utf-8')
+
     print('# testroot:', kwargs.get('testroot', 'root'))
     print('# builder:', app_.builder.name)
     print('# srcdir:', app_.srcdir)
```

------

Something else to investigate is rolling back `sys.modules`, as well as `sys.path`.

A

**Comment by AA-Turner** [comment]
With `pytest-randomly` installed, I get around 40 test failures, so there is still work to be done.

**Comment by AA-Turner** [comment]
Tests now run in parallel with `pytest-xdist` on Ubuntu (#13287)
