### ISSUE TITLE
Incomplete documentation for add_js_file() and add_css_file()

### ISSUE THREAD

**Issue by mgeier** [sphinx-doc/sphinx#12223]
### Describe the bug

- [ ] The examples do not include the CRC32 checksums added in #11415
- [ ] There should be a "changed in version 7.1" mentioning those checksums (https://www.sphinx-doc.org/en/master/changes.html#release-7-1-0-released-jul-24-2023)
- [ ] There should be a hint how JS/CSS files can be copied to the `_static` directory (see also https://github.com/sphinx-doc/sphinx/issues/11173#issuecomment-1496483665)
- [ ] It might also be helpful to mention that site authors (as opposed to extension developers) can use the config values `html_js_files` and `html_css_files` in combination with `html_static_path`?
- [ ] Maybe it could even be mentioned that files specified by extensions can be overridden by site authors by simply putting a file with the same name into their `html_static_path` (which currently doesn't fully work: #12096)?

### How to Reproduce

Look at https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file and https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_css_file.

**Comment by leonor16resende** [comment]
I will work on this!

**Comment by vidyanavghare08** [comment]
Hi
I’m a beginner and would like to improve the docs for add_js_file() and add_css_file() by adding CRC32 info, _static hints. Please let me know if that’s okay.
Thanks!

**Comment by AkshatJain34** [comment]
Hi, I’d like to work on this issue. can i take it
